#!/bin/env python

import sys, os

SConstruct = '''import sconsproject as project

# project.config.select(
#     packages.MPI(required=True),
#     packages.HDF5(required=True),
# )

# project.build([<sub_directories>])
'''

proj_SConscript = '''Import('env')
Export('env')

# Set the project name. This is passed on to sub-scripts.
env['PROJ'] = '%s'

# Call the 'src' SConscript. It will return a dictionary containing
# a mapping from the object path basename to the object.
obj_map = SConscript('src/SConscript', duplicate=0)

# Build static libraries and install them, if required.
if env['BUILD_STATIC_LIBS']:
    lib = env.Library('#' + env['BUILD'] + '/lib/' + env['PROJ'], obj_map.values())
    if env['PREFIX']:
        env.Install(env['PREFIX'] + '/lib', lib)

# Build shared libraries and install them, if required.
if env['BUILD_SHARED_LIBS'] and env['PREFIX']:
    env.SharedLibrary(env['PREFIX'] + '/lib/' + env['PROJ'], obj_map.values())

# Call the 'tests' SConscript, if required.
if env['BUILD_TESTS']:
    SConscript('tests/SConscript', duplicate=0, exports=['obj_map'])

# Build any applications.
if env['BUILD_APPS']:
    SConscript('apps/SConscript', duplicate=0, exports=['obj_map'])

# Call the 'exs' SConscript, if required. Examples will typically
# be untested demonstrations of code usage.
if env['BUILD_EXS']:
    SConscript('exs/SConscript', duplicate=0, exports=['obj_map'])

# Build documentation.
if env['BUILD_DOC']:
    SConscript('doc/SConscript', duplicate=0)
'''

src_SConscript = '''import os
Import('env')

# Try and use latest collections module, or use the OrderedDict in
# scons-config.
try:
    from collections import OrderedDict
except:
    from sconsconfig.utils.OrderedDict import OrderedDict

# Pick out the files we will be building.
hdrs = env.Glob('*.hh')
srcs = env.Glob('*.cc')

# Initialise an object map. This will map from the source file name to the objects they
# produce.
obj_map = OrderedDict()

# Install headers.
env.Install('#' + env['BUILD']  + '/include/' + env['PROJ'], hdrs)
if env['PREFIX']:
    env.Install(env['PREFIX'] + '/include/' + env['PROJ'], hdrs)

# Build source files.
for src in srcs:
    obj_map[os.path.basename(src.path)] = env.SharedObject(src)

Return('obj_map')
'''

tests_SConscript = '''Import('env', 'obj_map')
Export('env', 'obj_map')

srcs = (
#     ('source.cc', 'dep1.cc', 'dep2.cc', (range(num_ranks)),),
)

for src in srcs:
    if isinstance(src, str):
        objs = []
    else:
        objs = src[1:] if (len(src) > 1) else []
        objs = [obj_map[o] for o in objs]
        src = src[0]
    env.CxxTest([src] + objs)
'''

exs_SConscript = '''Import('env')

dst_dir = '#' + env['BUILD'] + '/exs/'
libs = env.get('LIBS', []) + ['discrete', 'parallel', 'containers', 'debug']

# env.Program(dst_dir + 'ex_name', 'source.cc', LIBS=libs)
'''

apps_SConscript = '''Import('env')

dst_dir = '#' + env['BUILD'] + '/bin/'
libs = env.get('LIBS', []) + ['discrete', 'parallel', 'containers', 'debug']

# env.Program(dst_dir + 'app_name', 'source.cc', LIBS=libs)
'''

def mkdir(dir):
    path = os.path.join(*dir)
    if not os.path.exists(path):
        os.makedirs(path)

def make_proj_tree(base, name):
    mkdir((base, name))

def make_sub_tree(base, name):
    sub_branches = ['src', 'tests', 'apps', 'exs', 'docs']
    branches = [(base, name, s) for s in sub_branches]
    for branch in branches:
        mkdir(branch)

def write(content, dst):
    path = os.path.join(*dst)
    if not os.path.exists(path):
        with open(path, 'w') as dst_file:
            dst_file.write(content)

def write_proj_content(base, name):
    write(SConstruct, (base, name, 'SConstruct'))

def write_sub_content(base, name):
    write(proj_SConscript%name, (base, name, 'SConscript'))
    write(src_SConscript, (base, name, 'src', 'SConscript'))
    write(tests_SConscript, (base, name, 'tests', 'SConscript'))
    write(exs_SConscript, (base, name, 'exs', 'SConscript'))
    write(apps_SConscript, (base, name, 'apps', 'SConscript'))

if __name__ == '__main__':
    try:
        cmd = sys.argv[1]
        name = sys.argv[2]
    except:
        print 'Wrong number of arguments'
        sys.exit()

    base = os.getcwd()

    if cmd.lower() == 'makeproj':
        make_proj_tree(base, name)
        write_proj_content(base, name)

    elif cmd.lower() == 'makesub':
        if not os.path.exists(os.path.join(base, 'SConstruct')):
            print 'Not in a project directory'
            sys.exit()
        make_sub_tree(base, name)
        write_sub_content(base, name)
